apiVersion: v1
kind: ServiceAccount
metadata:
  name: resume-api-sa
  namespace: default
---
apiVersion: policy.linkerd.io/v1beta3
kind: Server
metadata:
  name: redis-server
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: redis-db
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: resume-api
    ports:
    - protocol: TCP
      port: 6379
---
apiVersion: policy.linkerd.io/v1alpha1
kind: MeshTLSAuthentication
metadata:
  name: api-auth-mtls
  namespace: default
spec:
  identities:
    - "resume-api-sa.default.serviceaccount.cluster.local"
---
apiVersion: policy.linkerd.io/v1alpha1
kind: AuthorizationPolicy
metadata:
  name: redis-access-policy
  namespace: default
spec:
  targetRef:
    group: policy.linkerd.io
    kind: Server
    name: redis-server
  requiredAuthenticationRefs:
    - name: api-auth-mtls
      kind: MeshTLSAuthentication
      group: policy.linkerd.io
