apiVersion: v1
kind: Service
metadata:
  name: resume-service
spec:
  type: LoadBalancer
  selector:
    app: resume-api
  ports:
    - name: cloudflare-port
      protocol: TCP
      port: 8081
      targetPort: 5000
    - name: standard-port
      protocol: TCP
      port: 80
      targetPort: 5000
