apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resume-api
  template:
    metadata:
      labels:
        app: resume-api
    spec:
      # --- STEP 1: POD LEVEL SECURITY ---
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: resume-api
        image: ofirrosilyo/resume-api:latest
        imagePullPolicy: Always
        # --- STEP 2: CONTAINER LEVEL SECURITY ---
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        startupProbe:
          httpGet:
            path: /health
            port: 5000
          failureThreshold: 6
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          periodSeconds: 10
        env:
        - name: REDIS_HOST
          value: "redis-db"
