apiVersion: v1
kind: Service
metadata:
  name: resume-service
spec:
  type: LoadBalancer
  selector:
    app: resume-api
  ports:
    - name: cloudflare-port
      protocol: TCP
      port: 8081
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: resume-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: resume
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
