apiVersion: v1
kind: Service
metadata:
  name: resume-api
  namespace: default
spec:
  selector:
    app: resume-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
