apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resume-api
  template:
    metadata:
      labels:
        app: resume-api
    spec:
      containers:
      - name: resume-api
        # Updated to :latest to match your GitHub Action
        image: ofirrosilyo/resume-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: api-env-config
              key: REDIS_HOST
